@extends('layouts.Doc')

@section('title', 'Solicitud')

@section('content')

<table border=1 width=100% height: 30rem>
    <tr>
        <td>1
        </td>
        <td>2
        </td>
        <td>3
        </td>
        <td>4
        </td>
        <td>5
        </td>
        <td>6
        </td>
        <td>7
        </td>
    </tr>
    <tr>
        <td>A1
        </td>
        <td>A2
        </td>
        <td>A3
        </td>
        <td>A4
        </td>
        <td>A5
        </td>
        <td>A6
        </td>
        <td>A7
        </td>
    </tr>
    <tr>
        <td>B1
        </td>
        <td>B2
        </td>
        <td>B3
        </td>
        <td>B4
        </td>
        <td>B5
        </td>
        <td>B6
        </td>
        <td>B7
        </td>
    </tr>
    <tr>
        <td>C1
        </td>
        <td>C2
        </td>
        <td>C3
        </td>
        <td>C4
        </td>
        <td>C5
        </td>
        <td>C6
        </td>
        <td>C7
        </td>
    </tr>
    <tr>
        <td>D1
        </td>
        <td>D2
        </td>
        <td>D3
        </td>
        <td>D4
        </td>
        <td>D5
        </td>
        <td>D6
        </td>
        <td>D7
        </td>
    </tr>
    <tr>
        <td>E1
        </td>
        <td>E2
        </td>
        <td>E3
        </td>
        <td>E4
        </td>
        <td>E5
        </td>
        <td>E6
        </td>
        <td>E7
        </td>
    </tr>
    <tr>
        <td>F1
        </td>
        <td>F2
        </td>
        <td>F3
        </td>
        <td>F4
        </td>
        <td>F5
        </td>
        <td>F6
        </td>
        <td>F7
        </td>
    </tr>
    <tr>
        <td>G1
        </td>
        <td>G2
        </td>
        <td>G3
        </td>
        <td>G4
        </td>
        <td>G5
        </td>
        <td>G6
        </td>
        <td>G7
        </td>
    </tr>
    <tr>
        <td>H1
        </td>
        <td>H2
        </td>
        <td>H3
        </td>
        <td>H4
        </td>
        <td>H5
        </td>
        <td>H6
        </td>
        <td>H7
        </td>
    </tr>
    <tr>
        <td>I1
        </td>
        <td>I2
        </td>
        <td>I3
        </td>
        <td>I4
        </td>
        <td>I5
        </td>
        <td>I6
        </td>
        <td>I7
        </td>
    </tr>
    <tr>
        <td>J1
        </td>
        <td>J2
        </td>
        <td>J3
        </td>
        <td>J4
        </td>
        <td>J5
        </td>
        <td>J6
        </td>
        <td>J7
        </td>
    </tr>
    <tr>
        <td>K1
        </td>
        <td>K2
        </td>
        <td>K3
        </td>
        <td>K4
        </td>
        <td>K5
        </td>
        <td>K6
        </td>
        <td>K7
        </td>
    </tr>
    <tr>
        <td>L1
        </td>
        <td>L2
        </td>
        <td>L3
        </td>
        <td>L4
        </td>
        <td>L5
        </td>
        <td>L6
        </td>
        <td>L7
        </td>
    </tr>
    <tr>
        <td>M1
        </td>
        <td>M2
        </td>
        <td>M3
        </td>
        <td>M4
        </td>
        <td>M5
        </td>
        <td>M6
        </td>
        <td>M7
        </td>
    </tr>
    <tr>
        <td>N1
        </td>
        <td>N2
        </td>
        <td>N3
        </td>
        <td>N4
        </td>
        <td>N5
        </td>
        <td>N6
        </td>
        <td>N7
        </td>
    </tr>
    <tr>
        <td>O1
        </td>
        <td>O2
        </td>
        <td>O3
        </td>
        <td>O4
        </td>
        <td>O5
        </td>
        <td>O6
        </td>
        <td>O7
        </td>
    </tr>
    <tr>
        <td>P1
        </td>
        <td>P2
        </td>
        <td>P3
        </td>
        <td>P4
        </td>
        <td>P5
        </td>
        <td>P6
        </td>
        <td>P7
        </td>
    </tr>
    <tr>
        <td>Q1
        </td>
        <td>Q2
        </td>
        <td>Q3
        </td>
        <td>Q4
        </td>
        <td>Q5
        </td>
        <td>Q6
        </td>
        <td>Q7
        </td>
    </tr>
    <tr>
        <td>R1
        </td>
        <td>R2
        </td>
        <td>R3
        </td>
        <td>R4
        </td>
        <td>R5
        </td>
        <td>R6
        </td>
        <td>R7
        </td>
    </tr>
    <tr>
        <td>S1
        </td>
        <td>S2
        </td>
        <td>S3
        </td>
        <td>S4
        </td>
        <td>S5
        </td>
        <td>S6
        </td>
        <td>S7
        </td>
    </tr>
    <tr>
        <td>T1
        </td>
        <td>T2
        </td>
        <td>T3
        </td>
        <td>T4
        </td>
        <td>T5
        </td>
        <td>T6
        </td>
        <td>T7
        </td>
    </tr>
    <tr>
        <td>U1
        </td>
        <td>U2
        </td>
        <td>U3
        </td>
        <td>U4
        </td>
        <td>U5
        </td>
        <td>U6
        </td>
        <td>U7
        </td>
    </tr>
    <tr>
        <td>V1
        </td>
        <td>V2
        </td>
        <td>V3
        </td>
        <td>V4
        </td>
        <td>V5
        </td>
        <td>V6
        </td>
        <td>V7
        </td>
    </tr>
    <tr>
        <td>W1
        </td>
        <td>W2
        </td>
        <td>W3
        </td>
        <td>W4
        </td>
        <td>W5
        </td>
        <td>W6
        </td>
        <td>W7
        </td>
    </tr>
    <tr>
        <td>X1
        </td>
        <td>X2
        </td>
        <td>X3
        </td>
        <td>X4
        </td>
        <td>X5
        </td>
        <td>X6
        </td>
        <td>X7
        </td>
    </tr>
    <tr>
        <td>Y1
        </td>
        <td>Y2
        </td>
        <td>Y3
        </td>
        <td>Y4
        </td>
        <td>Y5
        </td>
        <td>Y6
        </td>
        <td>Y7
        </td>
    </tr>
    <tr>
        <td>Z1
        </td>
        <td>Z2
        </td>
        <td>Z3
        </td>
        <td>Z4
        </td>
        <td>Z5
        </td>
        <td>Z6
        </td>
        <td>Z7
        </td>
    </tr>
    <tr>
        <td>AA1
        </td>
        <td>AA2
        </td>
        <td>AA3
        </td>
        <td>AA4
        </td>
        <td>AA5
        </td>
        <td>AA6
        </td>
        <td>AA7
        </td>
    </tr>
    <tr>
        <td>BB1
        </td>
        <td>BB2
        </td>
        <td>BB3
        </td>
        <td>BB4
        </td>
        <td>BB5
        </td>
        <td>BB6
        </td>
        <td>BB7
        </td>
    </tr>
    <tr>
        <td>CC1
        </td>
        <td>CC2
        </td>
        <td>CC3
        </td>
        <td>CC4
        </td>
        <td>CC5
        </td>
        <td>CC6
        </td>
        <td>CC7
        </td>
    </tr>
    <tr>
        <td>DD1
        </td>
        <td>DD2
        </td>
        <td>DD3
        </td>
        <td>DD4
        </td>
        <td>DD5
        </td>
        <td>DD6
        </td>
        <td>DD7
        </td>
    </tr>
    <tr>
        <td>EE1
        </td>
        <td>EE2
        </td>
        <td>EE3
        </td>
        <td>EE4
        </td>
        <td>EE5
        </td>
        <td>EE6
        </td>
        <td>EE7
        </td>
    </tr>
    <tr>
        <td>FF1
        </td>
        <td>FF2
        </td>
        <td>FF3
        </td>
        <td>FF4
        </td>
        <td>FF5
        </td>
        <td>FF6
        </td>
        <td>FF7
        </td>
    </tr>
    <tr>
        <td>GG1
        </td>
        <td>GG2
        </td>
        <td>GG3
        </td>
        <td>GG4
        </td>
        <td>GG5
        </td>
        <td>GG6
        </td>
        <td>GG7
        </td>
    </tr>
    <tr>
        <td>HH1
        </td>
        <td>HH2
        </td>
        <td>HH3
        </td>
        <td>HH4
        </td>
        <td>HH5
        </td>
        <td>HH6
        </td>
        <td>HH7
        </td>
    </tr>
    <tr>
        <td>II1
        </td>
        <td>II2
        </td>
        <td>II3
        </td>
        <td>II4
        </td>
        <td>II5
        </td>
        <td>II6
        </td>
        <td>II7
        </td>
    </tr>
    <tr>
        <td>JJ1
        </td>
        <td>JJ2
        </td>
        <td>JJ3
        </td>
        <td>JJ4
        </td>
        <td>JJ5
        </td>
        <td>JJ6
        </td>
        <td>JJ7
        </td>
    </tr>
    <tr>
        <td>KK1
        </td>
        <td>KK2
        </td>
        <td>KK3
        </td>
        <td>KK4
        </td>
        <td>KK5
        </td>
        <td>KK6
        </td>
        <td>KK7
        </td>
    </tr>
    <tr>
        <td>LL1
        </td>
        <td>LL2
        </td>
        <td>LL3
        </td>
        <td>LL4
        </td>
        <td>LL5
        </td>
        <td>LL6
        </td>
        <td>LL7
        </td>
    </tr>
    <tr>
        <td>MM1
        </td>
        <td>MM2
        </td>
        <td>MM3
        </td>
        <td>MM4
        </td>
        <td>MM5
        </td>
        <td>MM6
        </td>
        <td>MM7
        </td>
    </tr>
    <tr>
        <td>NN1
        </td>
        <td>NN2
        </td>
        <td>NN3
        </td>
        <td>NN4
        </td>
        <td>NN5
        </td>
        <td>NN6
        </td>
        <td>NN7
        </td>
    </tr>
    <tr>
        <td>OO1
        </td>
        <td>OO2
        </td>
        <td>OO3
        </td>
        <td>OO4
        </td>
        <td>OO5
        </td>
        <td>OO6
        </td>
        <td>OO7
        </td>
    </tr>
    <tr>
        <td>PP1
        </td>
        <td>PP2
        </td>
        <td>PP3
        </td>
        <td>PP4
        </td>
        <td>PP5
        </td>
        <td>PP6
        </td>
        <td>PP7
        </td>
    </tr>
    <tr>
        <td>QQ1
        </td>
        <td>QQ2
        </td>
        <td>QQ3
        </td>
        <td>QQ4
        </td>
        <td>QQ5
        </td>
        <td>QQ6
        </td>
        <td>QQ7
        </td>
    </tr>
    <tr>
        <td>RR1
        </td>
        <td>RR2
        </td>
        <td>RR3
        </td>
        <td>RR4
        </td>
        <td>RR5
        </td>
        <td>RR6
        </td>
        <td>RR7
        </td>
    </tr>
    <tr>
        <td>SS1
        </td>
        <td>SS2
        </td>
        <td>SS3
        </td>
        <td>SS4
        </td>
        <td>SS5
        </td>
        <td>SS6
        </td>
        <td>SS7
        </td>
    </tr>



</table>
<!--div class="container">  <!-- $Solicitud antes era $Solicitud MC>
    <div class="row">
        <div class="col text-left">
            <div><h4>Reporte:</h4>
            Fecah: {{$Solicitud->created_at}}</div></br></br></br></br></br></br>
            <div> FIRMA:
            <img src="../public/firma.png" height="90px" width="200px" alt="FIRMA"></div>
        </div>
        <div class="col text-right">
            <img src="data:image/svg+xml;base64, {{base64_encode($valor1)}}"><br>
            Código de la solicitud.
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th scope="col" colspan="2">DATOS DEL EQUIPO</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                    <th scope="row">ID Equipo</th>
                    <td>{{$Solicitud->ID_inv}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Nombre</th>
                    <td>{{$Solicitud->Nombre}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Marca</th>
                    <td>{{$Solicitud->Marca}}</td>
                    <tr>
                    <th scope="row">Modelo</th>
                    <td>{{$Solicitud->Modelo}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Numero de série</th>
                    <td>{{$Solicitud->Num_de_serie}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Area</th>
                    <td>{{$Solicitud->Area}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Tipo</th>
                    <td>{{$Solicitud->Tipo}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Ubicación</th>
                    <td>{{$Solicitud->Ubicacion}}</td>
                    </tr>
                    <tr>
                    <th scope="row">Mantenimiento brindado por:</th>
                    <td>{{$Solicitud->Mnto}}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col text-right">
            <img class="" src="data:image/svg+xml;base64, {{base64_encode($valor2)}}"><br>
            Código del equipo.
        </div>
        
        <div><p>Datos:</p>
            Fallo: {{$Solicitud->Descripcion_del_fallo}}</br>
            Observaciones: {{$Solicitud->Observaciones}}</div>
        
    </div>
</div-->
@endsection